# Base configs
baseurl: "https://mmtr.me"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_tag_manager: "GTM-5MTGXDH"

# UI configs
title: "Photography by mametora"
subtitle: "Where Light Meets Emotion"
author: "mametora"
header:
 title: "Photography"
 subtitle: "by mametora"
footer:
 name: "Hey there, my name is mametora"
 bio: "I am a street photographer inspired by the everyday life of the city and its people. For the past two years, I’ve been capturing the raw beauty and emotions hidden in urban landscapes, revealing the stories that often go unnoticed. My work explores the intricate relationship between people and the environments they inhabit, finding meaning in the mundane. I’ve shared my photography through publications at Comiket, and I strive to show that there’s beauty and emotion in every corner of the world, waiting to be discovered."
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
twitter_username: "@mmtrum"
social_urls:
  twitter: "https://twitter.com/mmtrum"
  instagram: "https://www.instagram.com/nyahtora"
  # dribbble: ""
  # linkedin: ""
  github: "https://github.com/mametora"
